/**
 * One rigged Momo Lottie act per onboarding screen.
 * Stages 1–8 are `app/(auth)/welcome.tsx`; stage 9 is `app/(auth)/momo-intro.tsx`.
 * The animations are vector shape layers generated by `tools/build-momo-lottie.mjs`
 * (head, ears, eyes, glasses, mouth, cap, torso, two-part arms, legs and tail all move).
 * Pure data (no React Native imports) so it can be unit tested under node.
 */
export type MomoAnimation =
  | 'wave'
  | 'tip-cap'
  | 'listen'
  | 'point'
  | 'think'
  | 'present-book'
  | 'march'
  | 'proud'
  | 'cheer';

export type MomoStepNumber = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

/** Every act is a seamless 120-frame loop at 30 fps. */
export const MOMO_FRAME_COUNT = 120;

export interface MomoStep {
  animation: MomoAnimation;
  /** Frame shown as a still pose when Reduce Motion is on. */
  stillFrame: number;
  /** Accessibility label for the illustration. */
  label: string;
}

export const MOMO_STEPS: Record<MomoStepNumber, MomoStep> = {
  1: { animation: 'wave', stillFrame: 30, label: 'Momo waves hello' },
  2: { animation: 'tip-cap', stillFrame: 44, label: 'Momo tips its cap hello' },
  3: { animation: 'listen', stillFrame: 40, label: 'Momo tilts its head to listen' },
  4: { animation: 'point', stillFrame: 30, label: 'Momo points to your study choices' },
  5: { animation: 'think', stillFrame: 30, label: 'Momo thinks about your subject' },
  6: { animation: 'present-book', stillFrame: 36, label: 'Momo holds up an open book' },
  7: { animation: 'march', stillFrame: 8, label: 'Momo marches to a daily rhythm' },
  8: { animation: 'proud', stillFrame: 40, label: 'Momo proudly shows your sample' },
  9: { animation: 'cheer', stillFrame: 0, label: 'Momo cheers with arms raised' },
};
