// Generated by tools/momo-motion/build-handoff.mjs. Source JSON loads on demand.
import type { AnimationObject } from 'lottie-react-native';

export const MOMO_MOTION = {
  'momo-wave': {
    source: () => require('@/assets/animations/momo-motion/momo-wave.json') as AnimationObject,
    loop: true, frames: 120, stillFrame: 0,
    label: "Momo · Wave", decorativeBurst: false,
  },
  'momo-welcome': {
    source: () => require('@/assets/animations/momo-motion/momo-welcome.json') as AnimationObject,
    loop: true, frames: 120, stillFrame: 0,
    label: "Momo · Welcome", decorativeBurst: false,
  },
  'momo-ready': {
    source: () => require('@/assets/animations/momo-motion/momo-ready.json') as AnimationObject,
    loop: true, frames: 120, stillFrame: 0,
    label: "Momo · Ready", decorativeBurst: false,
  },
  'momo-reading': {
    source: () => require('@/assets/animations/momo-motion/momo-reading.json') as AnimationObject,
    loop: true, frames: 120, stillFrame: 0,
    label: "Momo · Reading", decorativeBurst: false,
  },
  'momo-bow': {
    source: () => require('@/assets/animations/momo-motion/momo-bow.json') as AnimationObject,
    loop: true, frames: 120, stillFrame: 0,
    label: "Momo · Bow", decorativeBurst: false,
  },
  'momo-cheer': {
    source: () => require('@/assets/animations/momo-motion/momo-cheer.json') as AnimationObject,
    loop: true, frames: 120, stillFrame: 0,
    label: "Momo · Cheer", decorativeBurst: false,
  },
  'momo-listen': {
    source: () => require('@/assets/animations/momo-motion/momo-listen.json') as AnimationObject,
    loop: true, frames: 120, stillFrame: 0,
    label: "Momo · Listen", decorativeBurst: false,
  },
  'momo-point': {
    source: () => require('@/assets/animations/momo-motion/momo-point.json') as AnimationObject,
    loop: true, frames: 120, stillFrame: 0,
    label: "Momo · Point", decorativeBurst: false,
  },
  'momo-present': {
    source: () => require('@/assets/animations/momo-motion/momo-present.json') as AnimationObject,
    loop: true, frames: 120, stillFrame: 0,
    label: "Momo · Present", decorativeBurst: false,
  },
  'momo-proud': {
    source: () => require('@/assets/animations/momo-motion/momo-proud.json') as AnimationObject,
    loop: true, frames: 120, stillFrame: 0,
    label: "Momo · Proud", decorativeBurst: false,
  },
  'momo-rest': {
    source: () => require('@/assets/animations/momo-motion/momo-rest.json') as AnimationObject,
    loop: true, frames: 120, stillFrame: 0,
    label: "Momo · Rest", decorativeBurst: false,
  },
  'momo-thinking': {
    source: () => require('@/assets/animations/momo-motion/momo-thinking.json') as AnimationObject,
    loop: true, frames: 120, stillFrame: 0,
    label: "Momo · Thinking", decorativeBurst: false,
  },
  'momo-hero': {
    source: () => require('@/assets/animations/momo-motion/momo-hero.json') as AnimationObject,
    loop: true, frames: 120, stillFrame: 0,
    label: "Momo · Hero", decorativeBurst: false,
  },
  'streak-fire': {
    source: () => require('@/assets/animations/momo-motion/streak-fire.json') as AnimationObject,
    loop: true, frames: 60, stillFrame: 0,
    label: "Streak · Fire", decorativeBurst: false,
  },
  'streak-ignite': {
    source: () => require('@/assets/animations/momo-motion/streak-ignite.json') as AnimationObject,
    loop: false, frames: 42, stillFrame: 34,
    label: "Streak · Ignite", decorativeBurst: false,
  },
  'confetti-burst': {
    source: () => require('@/assets/animations/momo-motion/confetti-burst.json') as AnimationObject,
    loop: false, frames: 96, stillFrame: 0,
    label: "Celebration · Confetti", decorativeBurst: true,
  },
  'confetti-gentle': {
    source: () => require('@/assets/animations/momo-motion/confetti-gentle.json') as AnimationObject,
    loop: false, frames: 84, stillFrame: 0,
    label: "Celebration · Gentle", decorativeBurst: true,
  },
  'book-loading': {
    source: () => require('@/assets/animations/momo-motion/book-loading.json') as AnimationObject,
    loop: true, frames: 72, stillFrame: 0,
    label: "Preparing study material", decorativeBurst: false,
  },
  'document-upload': {
    source: () => require('@/assets/animations/momo-motion/document-upload.json') as AnimationObject,
    loop: true, frames: 60, stillFrame: 0,
    label: "Uploading a document", decorativeBurst: false,
  },
  'document-scan': {
    source: () => require('@/assets/animations/momo-motion/document-scan.json') as AnimationObject,
    loop: true, frames: 60, stillFrame: 0,
    label: "Reading a document", decorativeBurst: false,
  },
  'reviewer-ready': {
    source: () => require('@/assets/animations/momo-motion/reviewer-ready.json') as AnimationObject,
    loop: false, frames: 42, stillFrame: 41,
    label: "Reviewer completed", decorativeBurst: false,
  },
  'answer-correct': {
    source: () => require('@/assets/animations/momo-motion/answer-correct.json') as AnimationObject,
    loop: false, frames: 24, stillFrame: 23,
    label: "Correct answer feedback", decorativeBurst: false,
  },
  'answer-retry': {
    source: () => require('@/assets/animations/momo-motion/answer-retry.json') as AnimationObject,
    loop: false, frames: 24, stillFrame: 23,
    label: "Supportive retry feedback", decorativeBurst: false,
  },
  'xp-reward': {
    source: () => require('@/assets/animations/momo-motion/xp-reward.json') as AnimationObject,
    loop: false, frames: 42, stillFrame: 41,
    label: "XP awarded after a study session", decorativeBurst: false,
  },
  'coin-reward': {
    source: () => require('@/assets/animations/momo-motion/coin-reward.json') as AnimationObject,
    loop: false, frames: 42, stillFrame: 41,
    label: "Momo Coins earned", decorativeBurst: false,
  },
  'heart-refill': {
    source: () => require('@/assets/animations/momo-motion/heart-refill.json') as AnimationObject,
    loop: false, frames: 60, stillFrame: 59,
    label: "Heart restored", decorativeBurst: false,
  },
  'offline-saved': {
    source: () => require('@/assets/animations/momo-motion/offline-saved.json') as AnimationObject,
    loop: false, frames: 42, stillFrame: 41,
    label: "Study set available offline", decorativeBurst: false,
  },
  'sync-working': {
    source: () => require('@/assets/animations/momo-motion/sync-working.json') as AnimationObject,
    loop: true, frames: 60, stillFrame: 0,
    label: "Pending study progress syncing", decorativeBurst: false,
  },
} as const;

export type MomoMotionName = keyof typeof MOMO_MOTION;

export type MotionPlayback = 'hidden' | 'still' | 'paused' | 'playing';

export function motionPlayback({ reducedMotion, active, focused, completed, decorativeBurst }: {
  reducedMotion: boolean; active: boolean; focused: boolean; completed: boolean; decorativeBurst: boolean;
}): MotionPlayback {
  if (reducedMotion) return decorativeBurst ? 'hidden' : 'still';
  if (!active || !focused) return 'paused';
  return completed ? 'still' : 'playing';
}
