// Generated by tools/momo-shop-motion/build-handoff.mjs.
import type { AnimationObject } from 'lottie-react-native';
export const SHOP_MOTION = {
  'shop-credit-pouch': { source: () => require('@/assets/animations/momo-shop/shop-credit-pouch.json') as AnimationObject, loop: false, frames: 60, stillFrame: 59, label: "Little Pouch", decorativeBurst: false },
  'shop-credit-backpack': { source: () => require('@/assets/animations/momo-shop/shop-credit-backpack.json') as AnimationObject, loop: false, frames: 60, stillFrame: 59, label: "Momo's Backpack", decorativeBurst: false },
  'shop-credit-vault': { source: () => require('@/assets/animations/momo-shop/shop-credit-vault.json') as AnimationObject, loop: false, frames: 60, stillFrame: 59, label: "Treasure Vault", decorativeBurst: false },
  'shop-heart-single': { source: () => require('@/assets/animations/momo-shop/shop-heart-single.json') as AnimationObject, loop: false, frames: 60, stillFrame: 59, label: "Single Heart", decorativeBurst: false },
  'shop-heart-five': { source: () => require('@/assets/animations/momo-shop/shop-heart-five.json') as AnimationObject, loop: false, frames: 60, stillFrame: 59, label: "High Five", decorativeBurst: false },
  'shop-heart-bowl': { source: () => require('@/assets/animations/momo-shop/shop-heart-bowl.json') as AnimationObject, loop: false, frames: 60, stillFrame: 59, label: "Full Bowl", decorativeBurst: false },
  'shop-hint-credits': { source: () => require('@/assets/animations/momo-shop/shop-hint-credits.json') as AnimationObject, loop: false, frames: 60, stillFrame: 59, label: "Quick Hint", decorativeBurst: false },
  'shop-special-credits': { source: () => require('@/assets/animations/momo-shop/shop-special-credits.json') as AnimationObject, loop: false, frames: 60, stillFrame: 59, label: "Momo's Special", decorativeBurst: false },
  'shop-xp-badge': { source: () => require('@/assets/animations/momo-shop/shop-xp-badge.json') as AnimationObject, loop: false, frames: 60, stillFrame: 59, label: "Study XP", decorativeBurst: false },
  'shop-exchange-credits': { source: () => require('@/assets/animations/momo-shop/shop-exchange-credits.json') as AnimationObject, loop: false, frames: 60, stillFrame: 59, label: "XP → Credits", decorativeBurst: false },
  'shop-exchange-hearts': { source: () => require('@/assets/animations/momo-shop/shop-exchange-hearts.json') as AnimationObject, loop: false, frames: 60, stillFrame: 59, label: "XP → Hearts", decorativeBurst: false },
  'shop-xp-needed': { source: () => require('@/assets/animations/momo-shop/shop-xp-needed.json') as AnimationObject, loop: false, frames: 60, stillFrame: 59, label: "Keep Studying", decorativeBurst: false },
} as const;
export type ShopMotionName = keyof typeof SHOP_MOTION;
